[tool.ruff]
line-length = 120
target-version = "py310"
exclude = ["*/migrations/*"]

select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "DJ",  # django
  "UP",  # pyupgrade,
  "I",   # isort

]

[tool.ruff.isort]